# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    restart: always
    env_file:
      - ./packages/server/.env
    ports:
      - "3306:3306" 
    container_name: mysql-db    
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    container_name: adminer
    networks:
      - mynetwork

  redis-server:
    restart: always
    image: redis
    container_name: redis-server
    ports:
      - "6380:6379"
    volumes:
      - ./redis:/data
    networks:
      - mynetwork

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local

networks:
  mynetwork:
    driver: bridge
